### ISSUE TITLE
Remove pull request template

### ISSUE THREAD

**Issue by cortadocodes** [octue/.github#2]
Once we roll out continuous deployment to all repositories, we won't need the pull request template anymore, so we can remove it. Leaving it here means it is still used before the `update-pull-request/description` job has run, prompting developers to start filling in the template when the job completes and removes whatever they've just written (or producing a race condition).

**Comment by thclark** [comment]
I disagree that it should be removed. I think we should alter it to comprise a top section, with comments that help guide the developer to write a good release summary/overview, and which contains the bounding strings for the release notes.
I’m not sure how we handle the race condition, though.

**Comment by cortadocodes** [comment]
Ah yes that's a good idea. I'll open a PR. The race condition is probably quite unlikely as most developers won't be going immediately to write a PR description when the PR is first created.
